/* 부서정보 테이블 */
CREATE TABLE DEPT_INFO(
	DI_ID VARCHAR2(20) PRIMARY KEY,
	DD_TITLE VARCHAR2(50), /* 프로젝트 고유번호 */
	DI_DEPT VARCHAR2(30),
	DI_STATUS VARCHAR2(20)
);
/* 부서문서 테이블 */
CREATE TABLE DEPT_DOC(
	DD_ID VARCHAR2(20) PRIMARY KEY,
	DD_TITLE VARCHAR2(50),
	DD_WRITER VARCHAR2(15),
	DD_CONTENT VARCHAR2(1000),
	DD_REGDATE DATE,
	DI_ID VARCHAR2(20)
);
/* 부서파일함 테이블 */
CREATE TABLE DEPT_BOX(
	DB_ID VARCHAR2(20),
	DB_WRITER VARCHAR2(15),
	DB_FILE VARCHAR2(300),
	DB_REGDATE DATE,
	DI_ID VARCHAR2(20)
);
/* 부서문서 첨부파일 */
CREATE TABLE DEPT_FILE(
	DF_ID VARCHAR2(20),
	DF_FILE VARCHAR2(300),
	DF_REGDATE DATE,
	DD_ID VARCHAR2(20)
);
/* 공통문서 테이블*/
CREATE TABLE COMMON_DOC(
	CD_ID VARCHAR2(20),
	CD_TITLE VARCHAR2(50),
	CD_WRITER VARCHAR2(15),
	CD_CONTENT VARCHAR2(1000),
	CD_REGDATE DATE,
	DI_ID VARCHAR2(20)
);
/* 공통문서 첨부파일 */
CREATE TABLE COMMON_FILE(
	CF_ID VARCHAR2(20),
	CF_FILE VARCHAR2(300),
	CF_REGDATE DATE,
	CD_ID VARCHAR2(20)
);